n = int(input("please enter n: "))
A = set(range(2, n, 2))
B = set(i for i in range(n) if i % 3 == 2)
C = A.union(B)
D = A.intersection(B)
E = A.difference(B)
F = A.symmetric_difference(B)
print(A)
print(B)
print(C)
print(D)
print(E)
print(F)
